// <auto-generated />
namespace CarRepairTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class YearendedoptionalforMakeandModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YearendedoptionalforMakeandModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241814067_Year ended optional for Make and Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
