// <auto-generated />
namespace CarRepairTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ne));
        
        string IMigrationMetadata.Id
        {
            get { return "201808222204048_ne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
